name: Deploy
run-name: Tech Priest ${{ github.actor }} is deploying the website 🚀

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Check out repository code
        uses: actions/checkout@v4

      - run: echo "Updating the code on AWS S3"
      - name : Updating the website
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id : ${{ secrets.ACCESS_AWS }}
          aws-secret-access-key : ${{ secrets.SECRET_ACCESS_AWS }}
          aws-region: eu-west-3
      - run: aws s3 sync ./Pronote s3://chiefbucket
